[project]
name = "rag-projetcs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ktilwebalo-hub", email = "ktilwebalo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=3.7.0",
    "pandas>=3.0.5",
]

[project.scripts]
rag-projetcs = "rag_projetcs:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
